EFDataApp/Controllers/CustomerController.cs
using EFDataApp.Domain;
using EFDataApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EFDataApp.Controllers
{
    public class CustomerController : Controller
    {
        private DataManager data;
        public CustomerController(DataManager data)
        {
            this.data = data;
        }
        public IActionResult Index(ProductOptions options)
        {
            return View(data.Products.GetProducts(options));
        }
    }
}

EFDataApp/Controllers/OrdersController.cs
using EFDataApp.Domain;
using EFDataApp.Domain.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EFDataApp.Controllers
{
    public class OrdersController : Controller
    {
        private DataManager data;
        public OrdersController(DataManager data)
        {
            this.data = data;
        }

        public IActionResult Index()
        {
            return View(data.Orders.GetOrders());
        }

        public IActionResult EditOrder(int id)
        {
            var products = data.Products.GetProducts();
            Order order = id == 0 ? new Order() : data.Orders.GetOrder(id);
            IDictionary<int, OrderLine> linesMap = order.Lines?.ToDictionary(l => l.ProductId) 
                ?? new Dictionary<int, OrderLine>();
            ViewBag.Lines = products.Select(p => linesMap.ContainsKey(p.Id) 
                ? linesMap[p.Id] : new OrderLine { Product = p, ProductId = p.Id, Quantity = 0});
            return View(order);
        }

        [HttpPost]
        public IActionResult AddOrUpdateOrder(Order order)
        {
            order.Lines = order.Lines.Where(l => l.Id > 0 || (l.Id == 0 && l.Quantity > 0)).ToArray();
            if(order.Id == 0)
            {
                data.Orders.AddOrder(order);
            }
            else
            {
                data.Orders.UpdateOrder(order);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult DeleteOrder(Order order)
        {
            data.Orders.DeleteOrder(order);
            return RedirectToAction(nameof(Index));
        }
    }
}

EFDataApp/Views/Shared/PageNav.cshtml
<div>
    @if (Model.HasPreviousPage)
    {
        <refer options="@Model.Options" page="@(Model.CurrentPage - 1)" class="btn btn-outline-primary" name="Previous" />
    }
    else
    {
        <refer options="@Model.Options" class="btn btn-outline-primary disabled" name="Previous" />
    }

    <refer options="@Model.Options" page="1" class="btn btn-outline-primary @(Model.CurrentPage == 1 ? "active" : "")" name="1" />


    @if ((Model.CurrentPage < 6 && (Model.TotalPages - Model.CurrentPage) > 6) || Model.TotalPages <= 9)
    {
        @for (int i = 2; i <= 8 && i < Model.TotalPages; i++)
        {
            <refer options="@Model.Options" page="@i" class="btn btn-outline-primary @(Model.CurrentPage == i ? "active" : "")" name="@(i == 8 ? "..." : i)" />
        }
    }
    else if (Model.CurrentPage > 6 && (Model.TotalPages - Model.CurrentPage) > 6)
    {
        @for (int i = Model.CurrentPage - 3; i <= Model.CurrentPage + 3 && i != Model.TotalPages; i++)
        {
            <refer options="@Model.Options" page="@i" class="btn btn-outline-primary @(Model.CurrentPage == i ? "active" : "")" name="@(i == Model.CurrentPage - 3 || i == Model.CurrentPage + 3 ? "..." : i)" />
        }
    }
    else
    {
        @for (int i = Model.TotalPages - 6; i < Model.TotalPages; i++)
        {
            <refer options="@Model.Options" page="@i" class="btn btn-outline-primary @(Model.CurrentPage == i ? "active" : "")" name="@(i == Model.TotalPages - 6 ? "..." : i)" />
        }
    }

    @if(Model.TotalPages > 1)
    { 
        <refer options="@Model.Options" page="Model.TotalPages" class="btn btn-outline-primary @(Model.CurrentPage == Model.TotalPages ? "active" : "")" name="@Model.TotalPages" />
    }
    

    @if (Model.HasNextPage)
    {
        <refer options="@Model.Options" page="@(Model.CurrentPage + 1)" class="btn btn-outline-primary @(!Model.HasNextPage ? "disabled" : "")" name="Next" />
    }
    else
    {
        <refer options="@Model.Options" class="btn btn-outline-primary disabled" name="Next" />
    }



    <form method="get" class="form-inline d-inline-block">

        <select name="options.PageSize" class="form-control ml-1 mr-1">
            @foreach (int val in new[] { 10, 25, 50, 100 })
            {
                <option value="@val" selected="@(Model.PageSize == val)">@val</option>
            }
        </select>

        <page-form options="@Model.Options" />
        <entity-form options="@Model.Options"/>
        
        <input type="hidden" name="options.CurrentPage" value="1" />
        <button type="submit" class="btn btn-secondary">Page Size</button>
    </form>
</div>

EFDataApp/Views/Shared/Table.cshtml
<table class="table">
    <tr>
        @foreach (string p in Model.Options.Properties)
        {
            <td><refer options="@Model.Options" sort="@p" name="@(p.IndexOf('.') == -1 ? p : p.Substring(0, p.IndexOf('.')))" /></td>
        }
    <td>
        <form>
            <details>
                <summary>Столбцы</summary>
                @foreach (string c in ViewBag.Cols)
                {
                    <p><input type="checkbox" checked="@(((string[])Model.Options.Properties).Contains(c))" value="@c" name="Options.Properties" />@(c.IndexOf('.') == -1 ? c : c.Substring(0, c.IndexOf('.')))</p>
                }
                <input type="submit" value="OK" />
            </details>

            <page-form options="@Model.Options" add-cols="@true" />
            <entity-form options="@Model.Options"/>

        </form>
        /
        <a asp-action="Create" asp-controller="@Model.Options.ControllerName">Создать</a>
    </td>
    </tr>
    @if (Model.Count == 0)
    {
        <tr><td colspan="@(((string[])Model.Options.Properties).Count() + 1)" class="text-center">No Data</td></tr>
    }
    else
    {
        @foreach (var item in Model) // Внешний цикл пробегает по объктам сущности
        {
            <tr>
                @foreach (string property in Model.Options.Properties) // Внутренний цикл пробегает по свойствам объкта сущности
                {
                    if (property.Contains(".")) // Если свойство сложное
                    {
                        var dividedProperty = property.Split("."); // Разделяем цепочку свойств свойство на массив названий каждого свойства в цепочке
                        var comPropery = item.GetType().GetProperty(dividedProperty[0]).GetValue(item); // Получаем значение первого свойства в цепочке

                        for (int i = 1; i < dividedProperty.Length; i++) // Пробегаем в цикле получая значение каждого элемента в цепочке пока не дойдем до самого нижнего с элементарным типом данных, значение которого можно отобразить в таблице
                        {
                            comPropery = comPropery.GetType().GetProperty(dividedProperty[i]).GetValue(comPropery);
                        }

                        <td>@comPropery</td>
                    }
                    else
                    {
                        if (property == "Name")
                        {
                            <td><a asp-action="Details" asp-controller="Home" asp-route-id="@item.Id" asp-route-returnUrl="@ViewContext.HttpContext.Request.PathAndQuery()">@item.GetType().GetProperty(property)?.GetValue(item)</a></td>
                        }
                        else
                        {
                            <td>@item.GetType().GetProperty(property)?.GetValue(item)</td> 
                            // С помощью рефлексии получаем тип объекта сущности
                            // из него получаем объект PropertyInfo по передаче названия(задаётся в массиве Properties) через параметр
                            // из него получаем знаечение свойства по передаче объекта который содержит это свойство также через параметр
                        }

                    }
                }
                <td>
                    <a asp-action="Edit" asp-controller="@Model.Options.ControllerName" asp-route-id="@item.Id">Изменить</a>
                    /
                    <a asp-action="Delete" asp-controller="@Model.Options.ControllerName" asp-route-id="@item.Id">Удалить</a>
                </td>
            </tr>
        }
    }

</table>

EFDataApp/Views/Shared/_Layout.cshtml
@using EFDataApp.Service
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        form {
            float: left;
            padding-left: 5px;
            
        }
        input.red{
            border: none;
            background-color: transparent;
            
        }
        div.imgweb {
            float: left;
            padding-left: 10px;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Index">Склады</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Заказы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Покупатель</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index" asp-route-returnUrl="@ViewContext.HttpContext.Request.PathAndQuery()">Корзина</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EFDataApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>, 
            телефон @Config.CompanyPhone
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>